clio_takehome:
  target: "{{env_var('DBT_TARGET') }}"
  outputs:
    dev:
      type: postgres
      host: "{{env_var('postgres_HOST') }}"
      user: "{{env_var('postgres_USER') }}"
      password: "{{env_var('postgres_PASSWORD') }}"
      port: 5432
      dbname: "{{env_var('postgres_DBNAME') }}"
      schema: "{{env_var('postgres_SCHEMA') }}"
      threads: 1
      connection_timeout: 10
